server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/STC
    username: postgres
    password: password
  jpa:
    hibernate:
     ddl-auto: update
     hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDIalect
      format-sql: true
    show-sql: true
  main:
    web-application-type: servlet