#debug: true
#
## Configure logging levels
#logging:
#  level:
#    root: info             # Set the default root logging level
#    org.springframework: debug   # Enable debug logging for all Spring components
#    com.yourpackage: debug        # Enable debug logging for your specific package
server:
  port: 8085
  address: 0.0.0.0
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ofarouk610@gmail.com
    password: Omar2004
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/STC
    username: postgres
    password: password
  jpa:
    hibernate:
     ddl-auto: update
     hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDIalect
      format-sql: true
    show-sql: true
  main:
    web-application-type: servlet